### ISSUE TITLE
Error when running rake

### ISSUE THREAD

**Issue by kimegede** [kerryb/todo-rails#1]
Hey Kerry,
Can you tell me, what I'm doing wrong here?

```
-> rake
/Users/kimegede/.rubies/ruby-2.2.3/bin/ruby -I/Users/kimegede/.gem/ruby/2.2.3/gems/rspec-core-3.2.2/lib:/Users/kimegede/.gem/ruby/2.2.3/gems/rspec-support-3.2.2/lib /Users/kimegede/.gem/ruby/2.2.3/gems/rspec-core-3.2.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...........

Finished in 0.05334 seconds (files took 1.19 seconds to load)
11 examples, 0 failures

/Users/kimegede/.rubies/ruby-2.2.3/bin/ruby -S bundle exec cucumber  --profile default
/Users/kimegede/.gem/ruby/2.2.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': incompatible library version - /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin_lexer_en.bundle (fatal)
    from /Users/kimegede/.gem/ruby/2.2.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/c_lexer.rb:9:in `[]'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:113:in `c'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:101:in `lexer'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:139:in `transition_table'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:128:in `build_transition_map'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:124:in `transition_map'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:91:in `initialize'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:68:in `new'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:68:in `push_machine'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/gherkin-2.12.2/lib/gherkin/parser/parser.rb:31:in `parse'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/feature_file.rb:37:in `parse'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime/features_loader.rb:28:in `block in load'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime/features_loader.rb:26:in `each'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime/features_loader.rb:26:in `load'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime/features_loader.rb:14:in `features'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:179:in `features'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/runtime.rb:49:in `run!'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/lib/cucumber/cli/main.rb:47:in `execute!'
    from /Users/kimegede/.gem/ruby/2.2.3/gems/cucumber-1.3.19/bin/cucumber:13:in `<top (required)>'
    from /Users/kimegede/.gem/ruby/2.2.3/bin/cucumber:23:in `load'
    from /Users/kimegede/.gem/ruby/2.2.3/bin/cucumber:23:in `<main>'
```

**Comment by kimegede** [comment]
Fixed

``` bash
gem uninstall gherkin --force
bundle install
```
